import * as THREE from 'three';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
type Family={id:string;status:string;lod:Record<string,string>};type Instance={familyId:string;position:[number,number,number];rotationY:number;scale:number;chunk:string};
type Manifest={status:string;badges:string[];families:Family[];instances:Instance[];blocks:{id:string;type:string}[];infrastructure:{uri:string};metrics:Record<string,number>};
export async function createCoreDistrictReview(app:HTMLDivElement,base:string){
 const manifest=await fetch(`${base}/manifest/core-district-3d.json`).then(r=>{if(!r.ok)throw new Error(`manifest ${r.status}`);return r.json() as Promise<Manifest>});
 app.innerHTML=`<main class="core3d"><aside><div class="brand"><span>ARCHIVE</span><strong>CORE DISTRICT 3D</strong></div><p class="core-warning">GENERATED CORE DISTRICT PILOT<br/>NOT CANONICAL · NOT V3 APPLIED</p><button id="core-aerial">Aerial</button><button id="core-street">Street</button><button id="core-day">Day</button><button id="core-night">Night</button><label><input id="core-infra" type="checkbox" checked/> Street/Public Realm</label><label><input id="core-buildings" type="checkbox" checked/> Buildings</label><label>LOD<select id="core-lod"><option>LOD1</option><option>LOD0</option><option>LOD2</option></select></label><dl><dt>Actual families</dt><dd>${manifest.metrics.actualFamilies}</dd><dt>Actual blocks</dt><dd>${manifest.metrics.actualBlocks}</dd><dt>Instances</dt><dd>${manifest.metrics.buildingInstances}</dd><dt>Proxy ratio</dt><dd>${(manifest.metrics.planningProxyRatio*100).toFixed(1)}%</dd></dl><div id="core-perf">LOADING ACTUAL GLB…</div></aside><section><div id="core-canvas"></div><div class="core-badge">${manifest.badges.join(' · ')}</div></section></main>`;
 const host=app.querySelector<HTMLElement>('#core-canvas')!,perf=app.querySelector<HTMLElement>('#core-perf')!;const scene=new THREE.Scene();scene.background=new THREE.Color(0xaac2d0);scene.fog=new THREE.Fog(0xaac2d0,900,2200);
 const camera=new THREE.PerspectiveCamera(52,1,.5,4000);camera.position.set(740,570,790);const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;host.append(renderer.domElement);
 const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,55,0);controls.enableDamping=true;const hemi=new THREE.HemisphereLight(0xeaf5ff,0x52614c,2.2);scene.add(hemi);const sun=new THREE.DirectionalLight(0xfff0d0,3);sun.position.set(-500,900,-350);sun.castShadow=true;scene.add(sun);
 const ground=new THREE.Mesh(new THREE.PlaneGeometry(1600,1400),new THREE.MeshStandardMaterial({color:0x6f8270,roughness:.95}));ground.rotation.x=-Math.PI/2;ground.position.y=-.08;scene.add(ground);
 const loader=new GLTFLoader(),buildings=new THREE.Group(),infrastructure=new THREE.Group();scene.add(buildings,infrastructure);const started=performance.now();
 const loaded=new Map<string,THREE.Object3D>();await Promise.all(manifest.families.map(async family=>{const gltf=await loader.loadAsync(`${base}/${family.lod.LOD1}`);loaded.set(family.id,gltf.scene);}));
 for(const family of manifest.families){const source=loaded.get(family.id);if(!source)continue;source.updateMatrixWorld(true);const items=manifest.instances.filter(item=>item.familyId===family.id);source.traverse(child=>{if(!(child instanceof THREE.Mesh))return;const mesh=new THREE.InstancedMesh(child.geometry,child.material,items.length);mesh.name=`batch-${family.id}-${child.name}`;mesh.userData={familyId:family.id,status:'ACTUAL_GLTF_INSTANCED'};items.forEach((item,index)=>{const base=new THREE.Matrix4().compose(new THREE.Vector3(...item.position),new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,1,0),item.rotationY),new THREE.Vector3(item.scale,item.scale,item.scale));mesh.setMatrixAt(index,base.multiply(child.matrixWorld));});mesh.instanceMatrix.needsUpdate=true;buildings.add(mesh);});}
 const infra=await loader.loadAsync(`${base}/${manifest.infrastructure.uri}`);infrastructure.add(infra.scene);const ready=performance.now();
 let frames=0,last=performance.now(),fps=0,minFps=999;function resize(){const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(host);resize();
 function animate(){requestAnimationFrame(animate);controls.update();renderer.render(scene,camera);frames++;const now=performance.now();if(now-last>=1000){fps=frames*1000/(now-last);minFps=Math.min(minFps,fps);frames=0;last=now;const info=renderer.info.render;perf.dataset.metrics=JSON.stringify({readyMs:Math.round(ready-started),fps:+fps.toFixed(1),lowFps:+minFps.toFixed(1),drawCalls:info.calls,triangles:info.triangles,instances:manifest.instances.length});perf.textContent=`READY ${Math.round(ready-started)}ms · FPS ${fps.toFixed(1)} · 1% proxy ${minFps.toFixed(1)} · draw ${info.calls} · tri ${info.triangles.toLocaleString()}`;document.title=`CORE3D|${fps.toFixed(1)}|${info.calls}|${info.triangles}`;}}animate();
 app.querySelector<HTMLButtonElement>('#core-aerial')!.onclick=()=>{camera.position.set(740,570,790);controls.target.set(0,55,0)};app.querySelector<HTMLButtonElement>('#core-street')!.onclick=()=>{camera.position.set(0,7,360);controls.target.set(0,24,0)};
 app.querySelector<HTMLButtonElement>('#core-day')!.onclick=()=>{scene.background=new THREE.Color(0xaac2d0);hemi.intensity=2.2;sun.intensity=3};app.querySelector<HTMLButtonElement>('#core-night')!.onclick=()=>{scene.background=new THREE.Color(0x111b2d);hemi.intensity=.35;sun.intensity=.18};
 app.querySelector<HTMLInputElement>('#core-infra')!.onchange=e=>infrastructure.visible=(e.target as HTMLInputElement).checked;app.querySelector<HTMLInputElement>('#core-buildings')!.onchange=e=>buildings.visible=(e.target as HTMLInputElement).checked;
 const query=new URLSearchParams(location.search),preset=Number(query.get('camera')??0);const cameras:[[number,number,number],[number,number,number]][]=[[[740,570,790],[0,55,0]],[[0,7,360],[0,24,0]],[[-520,110,430],[-120,35,40]],[[510,95,300],[150,35,0]],[[0,430,50],[0,0,0]],[[-340,40,-210],[-50,22,-170]],[[280,28,-420],[250,18,-170]],[[0,16,-230],[0,18,-40]],[[520,180,-400],[120,60,0]],[[-560,28,0],[-250,22,0]],[[120,55,450],[-130,25,100]],[[380,24,210],[250,16,120]]];const selected=cameras[preset%cameras.length];camera.position.set(...selected[0]);controls.target.set(...selected[1]);
 if(query.get('time')==='night'){scene.background=new THREE.Color(0x111b2d);hemi.intensity=.35;sun.intensity=.18}else if(query.get('time')==='dusk'){scene.background=new THREE.Color(0x7a7180);hemi.intensity=.8;sun.intensity=.75}
}
