import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import layout from '../../assets/world/archive-city-v2-layout.json';
import { createAdapter, type RuntimeMode } from './events';
import type { CityInstance, District } from './types';
import './style.css';

const app = document.querySelector<HTMLDivElement>('#app')!;
const colors: Record<District, number> = { archiveos: 0x29b6f6, market: 0xf9a825, nexus: 0x66bb6a, logistics: 0xef6c00, ledger: 0xab47bc, residential: 0x7cbf7c, infrastructure: 0x90a4ae, vehicle: 0x26c6da };
const mode = (import.meta.env.VITE_RUNTIME_DATA_MODE ?? 'mock') as RuntimeMode;
const archiveBase = import.meta.env.VITE_ARCHIVEOS_BASE_URL ?? '';
const runtimeBase = (import.meta.env.VITE_ARCHIVE_WORLD_ASSET_BASE_URL ?? '').replace(/\/$/, '');
app.innerHTML = `<main class="shell"><aside class="sidebar"><div class="brand"><span>ARCHIVE</span><strong>WORLD</strong></div><p class="eyebrow">DIGITAL TWIN · CITY V1</p><div class="button-stack" id="presets"></div><hr/><label>District filter</label><div class="filters" id="filters"></div><hr/><div class="metric"><span>Runtime mode</span><b id="runtime">${mode.toUpperCase()}</b></div><div class="metric"><span>FPS</span><b id="fps">--</b></div><div class="metric"><span>Visible assets</span><b id="visible">--</b></div><p class="hint">클릭: 자산 선택 · 드래그: 회전 · 스크롤: 확대</p></aside><section class="viewport"><div id="canvas"></div><div class="hud"><span id="load">도시 레이아웃 로딩 중…</span><span id="live-status"></span></div><aside class="selection" id="selection"><p class="eyebrow">ASSET INSPECTOR</p><h2>선택 없음</h2><dl><dt>상태</dt><dd>—</dd></dl></aside></section></main>`;
const host = document.querySelector<HTMLDivElement>('#canvas')!;
const overview = document.createElement('img'); overview.className = 'overview'; overview.src = 'v2/city-overview.png'; overview.alt = 'Archive City v2 overview'; document.querySelector<HTMLElement>('.viewport')!.append(overview);
const overviewUrls: Record<string, string> = { city: 'v2/city-overview.png', archiveos: 'v2/archiveos-overview.png', market: 'v2/market-overview.png', nexus: 'v2/nexus-overview.png', logistics: 'v2/logistics-overview.png', ledger: 'v2/ledger-overview.png', residential: 'v2/residential-overview.png', infrastructure: 'v2/infrastructure-overview.png' };
const renderer = new THREE.WebGLRenderer({ antialias: true, powerPreference: 'high-performance' }); renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); renderer.setSize(host.clientWidth, host.clientHeight); renderer.shadowMap.enabled = true; renderer.shadowMap.type = THREE.PCFSoftShadowMap; host.append(renderer.domElement);
const scene = new THREE.Scene(); scene.background = new THREE.Color(0x071018); scene.fog = new THREE.Fog(0x071018, 95, 280);
const camera = new THREE.PerspectiveCamera(48, host.clientWidth / host.clientHeight, 0.1, 450); camera.position.set(115, 105, 135);
const controls = new OrbitControls(camera, renderer.domElement); controls.target.set(0, 0, 0); controls.maxDistance = 250; controls.minDistance = 12; controls.maxPolarAngle = Math.PI * .48; controls.update();
scene.add(new THREE.HemisphereLight(0x9dd8ff, 0x10151b, 2.1)); const sun = new THREE.DirectionalLight(0xfff3d8, 2.6); sun.position.set(55, 90, 38); sun.castShadow = true; scene.add(sun);
const ground = new THREE.Mesh(new THREE.PlaneGeometry(230, 230), new THREE.MeshStandardMaterial({ color: 0x14232a, roughness: .92, metalness: .12 })); ground.rotation.x = -Math.PI / 2; ground.receiveShadow = true; scene.add(ground);
const groups = new Map<string, THREE.Group>(); const pickables: THREE.Object3D[] = [];
const districtRuntime = new Map<string, THREE.Group>(); const gltfLoader = new GLTFLoader();
function loadDistrictRuntime(id: string) {
  if (id === 'city' || districtRuntime.has(id) || !runtimeBase) return;
  gltfLoader.load(`${runtimeBase}/runtime/v2/${id}.glb`, (gltf) => { const group = gltf.scene; group.name = `Runtime_${id}`; scene.add(group); districtRuntime.set(id, group); }, undefined, () => { status.textContent = `RUNTIME UNAVAILABLE · ${id}`; });
}
function material(color: number, emissive = 0) { return new THREE.MeshStandardMaterial({ color, roughness: .58, metalness: .28, emissive, emissiveIntensity: emissive ? .35 : 0 }); }
function add(geometry: THREE.BufferGeometry, value: THREE.Material, group: THREE.Group, position: [number, number, number] = [0, 0, 0]) { const item = new THREE.Mesh(geometry, value); item.position.set(...position); item.castShadow = true; item.receiveShadow = true; group.add(item); return item; }
function createProxy(instance: CityInstance) {
  const group = new THREE.Group(); group.name = instance.instanceId; group.userData.instance = instance; const base = material(colors[instance.district]), dark = material(0x17212b), glass = material(0x6bd4e7, 0x113a4b), id = instance.assetId;
  if (instance.district === 'vehicle') { add(new THREE.BoxGeometry(3.2, 1.2, 6.2), base, group, [0, 1, 0]); add(new THREE.BoxGeometry(2.6, 1.4, 2.2), glass, group, [0, 2, .8]); for (const x of [-1.35, 1.35]) for (const z of [-2, 2]) { const wheel = add(new THREE.CylinderGeometry(.65, .65, .42, 16), dark, group, [x, .65, z]); wheel.rotation.z = Math.PI / 2; } if (id.includes('drone')) { group.clear(); add(new THREE.SphereGeometry(.7, 16, 12), base, group); for (const x of [-1.4, 1.4]) for (const z of [-1.4, 1.4]) { add(new THREE.BoxGeometry(.1, .1, 1.7), dark, group).rotation.y = Math.atan2(x, z); add(new THREE.CylinderGeometry(.55, .55, .06, 16), dark, group, [x, .12, z]); } } }
  else if (id.includes('tower')) { for (let level = 0; level < 5; level++) add(new THREE.CylinderGeometry(.28 - level*.03, .38 - level*.035, 2.8, 8), base, group, [0, 1.4 + level*2.7, 0]); add(new THREE.SphereGeometry(.35, 12, 8), glass, group, [0, 14.2, 0]); }
  else if (id.includes('substation') || id.includes('container')) { add(new THREE.BoxGeometry(11, .35, 8), dark, group, [0, .18, 0]); for (let x = -3; x <= 3; x += 3) for (let z = -2; z <= 2; z += 2) add(new THREE.BoxGeometry(2.4, 2.1, 1.8), x % 2 ? base : material(0xe06c32), group, [x, 1.25, z]); }
  else if (id.includes('road') || id.includes('yard') || id.includes('barrier') || id.includes('gate') || id.includes('signal')) { add(new THREE.BoxGeometry(8, .22, 8), dark, group, [0, .11, 0]); add(new THREE.BoxGeometry(.16, .025, 5.8), material(0xffd54f), group, [0, .24, 0]); }
  else if (instance.district === 'archiveos') {
    if (instance.instanceId.includes('control')) { add(new THREE.BoxGeometry(16, 44, 11), glass, group, [0, 24, 0]); add(new THREE.BoxGeometry(21, 4, 15), dark, group, [0, 2, 0]); add(new THREE.BoxGeometry(11, 2, 8), base, group, [0, 47, 0]); for (const x of [-7, 7]) add(new THREE.BoxGeometry(.42, 40, 12), base, group, [x, 24, 0]); }
    else if (instance.instanceId.includes('ai')) { add(new THREE.BoxGeometry(13, 29, 10), glass, group, [0, 16, 0]); add(new THREE.BoxGeometry(12, 8, 17), dark, group, [-9, 4, 0]); }
    else { add(new THREE.BoxGeometry(21, 10, 15), base, group, [0, 5, 0]); add(new THREE.BoxGeometry(15, 5, .3), glass, group, [0, 6, 7.6]); add(new THREE.CylinderGeometry(1, 1, .7, 16), material(0x29d8db, 0x0a3e45), group, [0, 10.5, 0]); }
  }
  else if (instance.district === 'market') {
    if (instance.instanceId.includes('commerce')) { add(new THREE.BoxGeometry(14, 29, 11), material(0x434080), group, [0, 16, 0]); add(new THREE.BoxGeometry(22, 8, 11), glass, group, [0, 4, 10]); add(new THREE.BoxGeometry(11, 2, 8), material(0x8c3cb7, 0x2c103d), group, [0, 31, 0]); }
    else if (instance.instanceId.includes('orders')) { add(new THREE.BoxGeometry(22, 18, 16), base, group, [0, 9, 0]); add(new THREE.BoxGeometry(17, 2, 12), glass, group, [0, 19, 0]); for (const x of [-8, -4, 0, 4, 8]) add(new THREE.BoxGeometry(.3, 12, .25), material(0x8749ae), group, [x, 10, 8.1]); }
    else { add(new THREE.BoxGeometry(25, 10, 18), dark, group, [0, 5, 0]); add(new THREE.BoxGeometry(12, 10, 12), base, group, [-5, 14, 0]); add(new THREE.BoxGeometry(7, .4, 12), glass, group, [10, 2.5, 0]); }
  }
  else if (instance.district === 'logistics') {
    if (id.includes('container')) { add(new THREE.BoxGeometry(32, .4, 24), material(0x374047), group, [0, .2, 0]); for (let row=-2; row<=2; row++) for (let col=-2; col<=2; col++) add(new THREE.BoxGeometry(4.4, 2.5 + (Math.abs(row)%2)*2.8, 3.4), (row+col)%2 ? base : material(0x244a6e), group, [col*5, 1.25+(Math.abs(row)%2)*1.4, row*4]); }
    else { const width=instance.instanceId.includes('distribution')?34:28, depth=instance.instanceId.includes('distribution')?24:18; add(new THREE.BoxGeometry(width, 10, depth), base, group, [0, 5, 0]); add(new THREE.BoxGeometry(width*.93, 1, depth*.9), material(0xd4dcda), group, [0, 10.5, 0]); for (let x=-width/2+3; x<width/2; x+=5) add(new THREE.BoxGeometry(3.4, 3.2, .25), dark, group, [x, 1.8, depth/2+.15]); add(new THREE.BoxGeometry(8, 10, 6), glass, group, [-width*.32, 7.5, -depth*.58]); }
  }
  else if (instance.district === 'nexus') {
    add(new THREE.BoxGeometry(30, 12, 24), base, group, [0, 6, 0]); add(new THREE.BoxGeometry(20, 2, 8), dark, group, [0, 13, 0]); if (instance.instanceId.includes('smart') || instance.instanceId.includes('materials')) { for (const x of [-10, 0, 10]) add(new THREE.CylinderGeometry(1.5, 1.8, 22, 12), material(0x738083), group, [x, 17, -5]); } for (const x of [-9, -3, 3, 9]) add(new THREE.BoxGeometry(.35, 12, .35), material(0x758287), group, [x, 6, 11]); for (const y of [6, 9]) add(new THREE.BoxGeometry(21, .35, .35), material(0xbc621c, 0x4a1600), group, [0, y, 11]);
  }
  else if (instance.district === 'ledger') {
    const height=instance.instanceId.includes('settlement')?36:instance.instanceId.includes('finance')?28:21, width=instance.instanceId.includes('settlement')?14:11; add(new THREE.BoxGeometry(width, height, width*.8), material(0x244260), group, [0, height/2+4, 0]); add(new THREE.BoxGeometry(width*.72, 2.2, width*.62), material(0x987224, 0x332204), group, [0, height+7, 0]); for (const x of [-width*.42,width*.42]) add(new THREE.BoxGeometry(.3,height*.96,width*.9), base, group,[x,height/2+4,0]); add(new THREE.BoxGeometry(width*1.35,4,width*1.2),dark,group,[0,2,0]);
  }
  else { const seed = [...id].reduce((sum, letter) => sum + letter.charCodeAt(0), 0), width = 8 + seed % 6, depth = 7 + seed % 5, height = 8 + seed % 9; add(new THREE.BoxGeometry(width, height, depth), base, group, [0, height/2, 0]); add(new THREE.BoxGeometry(width*.55, height*.36, depth*.65), glass, group, [0, height*1.18, 0]); }
  group.position.fromArray(instance.position); group.rotation.set(...instance.rotation); group.scale.fromArray(instance.scale ?? [1,1,1]); scene.add(group); groups.set(instance.instanceId, group); pickables.push(group); return group;
}
layout.instances.forEach((value) => createProxy(value as unknown as CityInstance));
for (const edge of layout.roadTopology.edges) { const a = layout.roadTopology.nodes.find((node) => node.nodeId === edge.from)!, b = layout.roadTopology.nodes.find((node) => node.nodeId === edge.to)!; const line = new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(...a.position), new THREE.Vector3(...b.position)]), new THREE.LineBasicMaterial({ color: 0x38525e, transparent: true, opacity: .75 })); line.position.y = .18; scene.add(line); }
const v2Presets = [{id:'city',label:'City',position:[260,240,250],target:[0,0,0]},{id:'archiveos',label:'ArchiveOS',position:[75,65,80],target:[0,0,0]},{id:'market',label:'Market',position:[-65,55,72],target:[-120,0,0]},{id:'nexus',label:'Nexus',position:[20,60,190],target:[-25,0,130]},{id:'logistics',label:'Logistics',position:[205,70,120],target:[125,0,20]},{id:'ledger',label:'Ledger',position:[95,60,-195],target:[15,0,-135]},{id:'residential',label:'Residential',position:[-185,60,190],target:[-120,0,130]}]; const presetHost = document.querySelector<HTMLDivElement>('#presets')!; for (const preset of v2Presets) { const button = document.createElement('button'); button.textContent = preset.label; button.onclick = () => { camera.position.fromArray(preset.position); controls.target.fromArray(preset.target); controls.update(); overview.src = overviewUrls[preset.id] ?? overviewUrls.city; overview.alt = `${preset.label} overview`; loadDistrictRuntime(preset.id); }; presetHost.append(button); }
const enabled = new Set<District>(['archiveos','market','nexus','logistics','ledger','residential','infrastructure','vehicle']); const filterHost = document.querySelector<HTMLDivElement>('#filters')!; for (const district of enabled) { const label = document.createElement('label'); label.className='filter'; label.innerHTML=`<input type="checkbox" checked /> ${district}`; const input=label.querySelector('input')!; input.onchange=()=>{ input.checked ? enabled.add(district) : enabled.delete(district); groups.forEach((group)=>{ if((group.userData.instance as CityInstance).district===district) group.visible=enabled.has(district); }); }; filterHost.append(label); }
const raycaster = new THREE.Raycaster(), pointer = new THREE.Vector2(), selection = document.querySelector<HTMLDivElement>('#selection')!; renderer.domElement.addEventListener('pointerdown',(event)=>{ pointer.x=event.offsetX/renderer.domElement.clientWidth*2-1; pointer.y=-(event.offsetY/renderer.domElement.clientHeight)*2+1; raycaster.setFromCamera(pointer,camera); const hit=raycaster.intersectObjects(pickables,true)[0]; if(!hit) return; let current:THREE.Object3D|null=hit.object; while(current && !current.userData.instance) current=current.parent; if(!current) return; const item=current.userData.instance as CityInstance; selection.innerHTML=`<p class="eyebrow">ASSET INSPECTOR</p><h2>${item.instanceId}</h2><dl><dt>Asset</dt><dd>${item.assetId}</dd><dt>District</dt><dd>${item.district}</dd><dt>LOD</dt><dd>${item.lodPolicy}</dd><dt>Binding</dt><dd>${item.statusBinding ?? '—'}</dd></dl>`; });
const adapter = createAdapter(mode, archiveBase), status = document.querySelector<HTMLSpanElement>('#live-status')!; status.textContent=mode==='mock'?'MOCK EVENT ADAPTER':'LIVE ADAPTER CONNECTING'; adapter.events().then((events)=>{status.textContent=mode==='mock'?`MOCK EVENTS · ${events.length}`:`LIVE · ${events.length}`;}).catch((error:Error)=>{status.textContent=`LIVE OFFLINE · ${error.message}`;});
const clock = new THREE.Clock(); let frames=0, elapsed=0; const fps=document.querySelector<HTMLSpanElement>('#fps')!, visible=document.querySelector<HTMLSpanElement>('#visible')!;
function animate(){ const delta=clock.getDelta(); frames++; elapsed+=delta; if(elapsed>.5){fps.textContent=String(Math.round(frames/elapsed));frames=0;elapsed=0;visible.textContent=String([...groups.values()].filter((value)=>value.visible).length);}controls.update();renderer.render(scene,camera);requestAnimationFrame(animate);} document.querySelector<HTMLSpanElement>('#load')!.textContent=`CITY V2 READY · ${layout.instances.length} instances`; window.addEventListener('resize',()=>{renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();});animate();
