type ReviewManifest={status:string;badges:string[];metrics:{metrics:{districtCount:number;buildingInstances:number;uniqueFamilies:number;blockVariantCount:number;streetSegments:number;transitStations:number;greenOpenSpaceRatio:number}};cameraPresets:string[]};
type Layer='buildings'|'streets'|'transit'|'green'|'publicRealm'|'height'|'density'|'status';
const LAYERS:Layer[]=['buildings','streets','transit','green','publicRealm','height','density','status'];

export async function createMetropolitanReview(app:HTMLDivElement,base:string){
 const response=await fetch(`${base}/stages/I-review-manifest.json`);if(!response.ok)throw new Error(`Metropolitan manifest unavailable: ${response.status}`);
 const manifest=await response.json() as ReviewManifest;const m=manifest.metrics.metrics;
 app.innerHTML=`<main class="metro-review"><aside><div class="brand"><span>ARCHIVE</span><strong>METROPOLITAN REVIEW</strong></div><p class="metro-warning">GENERATED METROPOLITAN PILOT<br/>NOT CANONICAL · NOT V3 APPLIED</p><label>District<select id="metro-district"><option>Full City</option><option>ArchiveOS Core</option><option>Ledger</option><option>Market</option><option>Nexus</option><option>Residential North</option><option>Residential South</option><option>Civic/Cultural</option><option>Logistics Edge</option></select></label><div id="metro-layers"></div><label>LOD<select><option>Auto</option><option>LOD0</option><option>LOD1</option><option>LOD2</option><option>Skyline Proxy</option></select></label><label>Time<select><option>Daylight</option><option>Dusk</option><option>Night</option></select></label><dl><dt>Districts</dt><dd>${m.districtCount}</dd><dt>Instances</dt><dd>${m.buildingInstances}</dd><dt>Families</dt><dd>${m.uniqueFamilies}</dd><dt>Block variants</dt><dd>${m.blockVariantCount}</dd><dt>Street edges</dt><dd>${m.streetSegments}</dd><dt>Transit stations</dt><dd>${m.transitStations}</dd><dt>Green/open</dt><dd>${(m.greenOpenSpaceRatio*100).toFixed(1)}%</dd></dl></aside><section><canvas id="metro-canvas" width="1400" height="900"></canvas><div class="metro-badge">${manifest.badges.join(' · ')}</div></section></main>`;
 const host=app.querySelector<HTMLElement>('#metro-layers')!;const active=new Set<Layer>(LAYERS);
 for(const layer of LAYERS){const label=document.createElement('label');label.className='filter';label.innerHTML=`<input type="checkbox" checked/> ${layer}`;label.querySelector('input')!.addEventListener('change',(event)=>{(event.target as HTMLInputElement).checked?active.add(layer):active.delete(layer);draw();});host.append(label);}
 const canvas=app.querySelector<HTMLCanvasElement>('#metro-canvas')!,ctx=canvas.getContext('2d')!;
 function draw(){ctx.fillStyle='#d8ddd9';ctx.fillRect(0,0,canvas.width,canvas.height);if(active.has('green')){ctx.fillStyle='#83a97c';ctx.fillRect(45,90,320,700);ctx.fillRect(380,360,850,120);}if(active.has('streets')){ctx.strokeStyle='#59636a';ctx.lineWidth=9;for(let x=120;x<1350;x+=110){ctx.beginPath();ctx.moveTo(x,30);ctx.lineTo(x,870);ctx.stroke();}for(let y=70;y<880;y+=95){ctx.beginPath();ctx.moveTo(30,y);ctx.lineTo(1370,y);ctx.stroke();}}if(active.has('transit')){ctx.strokeStyle='#cf715f';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(40,460);ctx.lineTo(1360,460);ctx.stroke();}if(active.has('buildings')){for(let y=0;y<7;y++)for(let x=0;x<11;x++){const h=22+((x*13+y*7)%55);ctx.fillStyle=active.has('status')&&((x+y)%9===0)?'#d4a84e':'#55778b';ctx.fillRect(105+x*110,100+y*95-h/2,48,h);}}}
 draw();
}
