import { exists, readJson } from './lib/files.mjs';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const mapping = await readJson(path.join(root, 'reports', 'asset-id-map.json'));
const incoming = await readJson(path.join(root, 'reports', 'incoming-inventory.json'));
const cards = [];
for (const asset of mapping.assets) {
  const metadata = await readJson(path.join(root, asset.metadataFile));
  cards.push({ assetId: asset.assetId, category: asset.category, source: 'meshy', status: metadata.validationStatus, triangles: metadata.triangles, bytes: metadata.fileSizes?.web ?? metadata.fileSizes?.source, lods: metadata.lods?.length ?? 0, animationReady: metadata.animationReady, preview: metadata.thumbnail ?? metadata.preview ?? null, warning: metadata.warnings?.join(', ') ?? '' });
}
for (const asset of incoming.assets) cards.push({ assetId: asset.filename.replace(/\.glb$/, ''), category: asset.classification, source: 'blender-generated', status: asset.validationStatus, triangles: null, bytes: asset.bytes, lods: 0, animationReady: asset.animationCount > 0, preview: null, warning: asset.warnings?.join(', ') ?? '' });
const tile = (asset) => `<article class="card" data-category="${asset.category}" data-source="${asset.source}" data-search="${asset.assetId.toLowerCase()}"><div class="thumb">${asset.preview ? `<img src="../${asset.preview}" alt="${asset.assetId}"/>` : '<span>NO PREVIEW</span>'}</div><h2>${asset.assetId}</h2><p><b>${asset.status}</b> · ${asset.source}</p><dl><dt>Triangles</dt><dd>${asset.triangles ?? '—'}</dd><dt>Size</dt><dd>${asset.bytes ?? '—'} bytes</dd><dt>LODs</dt><dd>${asset.lods}</dd><dt>Animation</dt><dd>${asset.animationReady ? 'ready' : 'none'}</dd></dl>${asset.warning ? `<small>${asset.warning}</small>` : ''}</article>`;
const html = `<!doctype html><html lang="ko"><meta charset="utf-8"><title>Archive-World Asset Catalog</title><style>body{font-family:system-ui;background:#071018;color:#dcecf3;margin:0;padding:28px}h1{margin:0}.toolbar{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}input,select{background:#102b3b;color:#fff;border:1px solid #24506a;padding:9px;border-radius:5px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(245px,1fr));gap:12px}.card{background:#0c1b26;border:1px solid #1c4055;border-radius:8px;padding:12px}.thumb{height:150px;background:#09131b;display:grid;place-items:center}.thumb img{width:100%;height:100%;object-fit:contain}.thumb span{color:#6b8a9a;font-size:11px}.card h2{font-size:14px;overflow-wrap:anywhere}.card p{color:#8dbfd2;font-size:12px}.card b{color:#6ee7ff}dl{display:grid;grid-template-columns:80px 1fr;font-size:12px}dt{color:#7fa7b9}dd{margin:0}small{color:#e5b565;display:block;margin-top:8px;overflow-wrap:anywhere}</style><h1>Archive-World Asset Catalog</h1><p>${cards.length}개 항목 · 로컬 검수 상태를 표시합니다. PENDING/REJECTED 자산은 manifest에 포함되지 않습니다.</p><div class="toolbar"><input id="q" placeholder="assetId 검색"><select id="category"><option value="">전체 category</option>${[...new Set(cards.map((x)=>x.category))].map((x)=>`<option>${x}</option>`).join('')}</select><select id="source"><option value="">전체 source</option><option>meshy</option><option>blender-generated</option></select></div><section class="grid">${cards.map(tile).join('')}</section><script>const cards=[...document.querySelectorAll('.card')],q=document.querySelector('#q'),c=document.querySelector('#category'),s=document.querySelector('#source');function f(){cards.forEach(x=>x.hidden=!(x.dataset.search.includes(q.value.toLowerCase())&&(!c.value||x.dataset.category===c.value)&&(!s.value||x.dataset.source===s.value)))}[q,c,s].forEach(x=>x.oninput=f)</script></html>`;
await mkdir(path.join(root, 'reports'), { recursive: true }); await writeFile(path.join(root, 'reports', 'asset-catalog.html'), html);
console.log(JSON.stringify({ catalog: 'reports/asset-catalog.html', assets: cards.length }));
